# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_dotaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotaz',
            name='odpovezeno',
            field=models.BooleanField(default=False),
        ),
    ]
